version: '3.8'

services:
  cuda:
    container_name: abnormal-detection-3DCNN
    hostname: 3DCNN
    image: loopbackkr/pytorch:1.8.1-cuda11.1-cudnn8
    tty: true
    stdin_open: true
    ports:
      - '8989:8097'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            # device_ids: ['0']
            capabilities: [gpu]
    shm_size: 64G
    volumes:
      - /root/projects/Video-Abnormal-Event-Detection-Based-on-Optical-Flow-and-3DCNN:/root/workspace
    environment:
      - TZ=<YOUR-TIME-ZONE>
      - DISPLAY=<YOUR-XSVR-ADDRESS>
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - MAIL_SENDER='<YOUR-MAIL-ADDRESS>'
      - MAIL_PASSWD='<YOUR-MAIL-PASSWORD>'
      - MAIL_RECEIVER='<RECEIVER'S-MAIL-ADDRESS>'
