version: '3.8'

services:
  cuda:
    container_name: abnormal-detection-3DCNN
    hostname: 3DCNN
    image: loopbackkr/pytorch:1.8.1-cuda11.1-cudnn8
    tty: true
    stdin_open: true
    ports:
      - '8989:8097'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            # device_ids: ['0']
            capabilities: [gpu]
    shm_size: 64G
    volumes:
      - /root/projects/Video-Abnormal-Event-Detection-Based-on-Optical-Flow-and-3DCNN:/root/workspace
    environment:
      - TZ=<YOUR-TIME-ZONE>
      - DISPLAY=<YOUR-XSVR-ADDRESS>
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - BEEP_MARIO='-f 130 -l 100 -n -f 262 -l 100 -n -f 330 -l 100 -n -f 392 -l 100 -n -f 523 -l 100 -n -f 660 -l 100 -n -f 784 -l 300 -n -f 660 -l 300 -n -f 146 -l 100 -n -f 262 -l 100 -n -f 311 -l 100 -n -f 415 -l 100 -n -f 523 -l 100 -n -f 622 -l 100 -n -f 831 -l 300 -n -f 622 -l 300 -n -f 155 -l 100 -n -f 294 -l 100 -n -f 349 -l 100 -n -f 466 -l 100 -n -f 588 -l 100 -n -f 699 -l 100 -n -f 933 -l 300 -n -f 933 -l 100 -n -f 933 -l 100 -n -f 933 -l 100 -n -f 1047 -l 400'
      - MAIL_SENDER='<YOUR-MAIL-ADDRESS>'
      - MAIL_PASSWD='<YOUR-MAIL-PASSWORD>'
      - MAIL_RECEIVER='<RECEIVER'S-MAIL-ADDRESS>'
